name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3  # Ensures CodeQL can analyze the project

      - name: Set CodeQL Path
        run: echo "CODEQL_PATH=$(which codeql)" >> $GITHUB_ENV  # Ensure the path to codeql is set

      - name: Run CodeQL query for "helloWorld" function
        run: |
          # Check if codeql is in the path and install if necessary
          if [ -z "$(which codeql)" ]; then
            echo "CodeQL not found, installing it manually" 
            wget https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
            unzip codeql-linux64.zip
            export PATH=$(pwd)/codeql:$PATH
          fi
      
          # Debug: Show the database location (should be set by the init step)
          echo "Using CodeQL database at $CODEQL_DATABASE"
      
          # Run the query using the correct database location
          codeql query run --database="$CODEQL_DATABASE" .github/queries/method.ql --output=results.bqrs

      
          # Decode the binary results into CSV format
          codeql bqrs decode --format=csv results.bqrs > result.txt
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-helloWorld-results
          path: result.txt










