name: CodeQL JavaScript Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL to upload results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # ✅ Step 1: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      # ✅ Step 2: Automatically Build the Project
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # ✅ Step 3: Run Custom CodeQL Query and Decode Results
      - name: Run CodeQL Query
        run: |
          mkdir -p results
          codeql database create js-codeql-db --language=javascript --source-root=src
          codeql query run --database=js-codeql-db .github/queries/method.ql --output=results/results.bqrs
          codeql bqrs decode --format=csv results/results.bqrs > results/results.csv

      # ✅ Step 4: Debug Query Results
      - name: Debug Query Results
        run: |
          echo "Checking if results.csv exists..."
          ls -l results/results.csv || echo "Error: results.csv not found!"

      # ✅ Step 5: Upload Query Results as an Artifact
      - name: Upload Query Results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-query-results
          path: results/results.csv











