name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3  # Ensures CodeQL can analyze the project

      - name: Run CodeQL query for "helloWorld" function
        run: |
          codeql query run --database=js-codeql-db --query=queries/helloWorldFunction.ql > result.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-helloWorld-results
          path: result.txt







