name: CodeQL JavaScript Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL to upload results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # ✅ Step 1: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      # ✅ Step 2: Automatically Build the Project
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # ✅ Step 3: Run CodeQL Queries Correctly (No "command not found" Errors)
      - name: Run CodeQL Queries
        uses: github/codeql-action/analyze@v3
        with:
          category: "custom-query"
          queries: .github/queries

      # ✅ Step 4: Upload Query Results as an Artifact
      - name: Upload Query Results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-query-results
          path: security-results.sarif









