name: CodeQL Custom Query Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze Code with CodeQL Custom Queries
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript # Adjust based on your project (e.g., python, java, csharp, go)

      - name: Run CodeQL Custom Queries
        uses: github/codeql-action/analyze@v3
        with:
          category: "custom-query"
          queries: .github/queries

      - name: Verify SARIF File Exists
        run: ls -la ./results

      - name: Upload CodeQL SARIF Results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-custom-results
          path: ./results/security-results.sarif

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./results/security-results.sarif










