name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Debug CodeQL Database
        run: |
          echo "CodeQL database is set to: $CODEQL_DATABASE"
          ls -la "$CODEQL_DATABASE"

      - name: Run CodeQL Query
        run: |
          if [ -z "$CODEQL_DATABASE" ]; then
            echo "Error: CODEQL_DATABASE is not set."
            exit 1
          fi

          codeql query run --database="$CODEQL_DATABASE" .github/queries/method.ql --output=results.bqrs

          # Decode results to CSV
          codeql bqrs decode --format=csv results.bqrs > result.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-helloWorld-results
          path: result.txt
