name: CodeQL JavaScript Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL to upload results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # ✅ Step 1: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      # ✅ Step 2: Automatically Build the Project
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # ✅ Step 3: Create a CodeQL Database (Optional but Recommended)
      - name: Create CodeQL Database
        run: |
          codeql database create js-codeql-db --language=javascript --source-root=src
          echo "CODEQL_DATABASE=$(pwd)/js-codeql-db" >> $GITHUB_ENV

      # ✅ Step 4: Run Custom Queries from queries/ Directory
      - name: Run CodeQL Queries
        run: |
          codeql query run --database="$CODEQL_DATABASE" .github/queries/method.ql --output=results.bqrs
          codeql bqrs decode --format=csv results.bqrs > result.txt

      # ✅ Step 5: Upload Query Results as an Artifact
      - name: Upload Query Results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-query-results
          path: result.txt








