name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # Required for CodeQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Debug CodeQL Database
        run: |
          echo "CodeQL database is set to: $CODEQL_DATABASE"
          if [ -z "$CODEQL_DATABASE" ]; then
            echo "CODEQL_DATABASE is not set! Creating a new database..."
            codeql database create js-codeql-db --language=javascript --source-root=src
            echo "CODEQL_DATABASE=$(pwd)/js-codeql-db" >> $GITHUB_ENV
          fi

      - name: Run CodeQL Query
        run: |
          codeql query run --database="$CODEQL_DATABASE" .github/queries/method.ql --output=results.bqrs
          codeql bqrs decode --format=csv results.bqrs > result.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-helloWorld-results
          path: result.txt





