name: CodeQL Custom Query Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze Code with CodeQL Custom Queries
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript # Adjust based on your repo's language

      - name: Run CodeQL Custom Queries
        uses: github/codeql-action/analyze@v3
        with:
          category: "custom-query-analysis"  # Unique category for analyze step
          queries: .github/queries  # Path to your custom queries
          output: ./results/security-results.sarif  # Explicit output location for SARIF file

      # ✅ Debug Step: Verify Output Directory and File
      - name: List files in results directory
        run: ls -la ./results || echo "Results directory not found"

      # ✅ Debug Step: Find SARIF Files in the Workspace
      - name: Find SARIF Files
        run: find . -name "*.sarif" || echo "No SARIF files found"

      # ✅ Upload CodeQL SARIF Results (With unique category)
      - name: Upload CodeQL SARIF Results
        uses: actions/upload-artifact@v4
        with:
          name: codeql-custom-results
          path: ./results/security-results.sarif

      # ✅ Upload SARIF to GitHub Security Alerts (With a different unique category)
      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: "custom-query-upload"  # Ensure this category is unique
          sarif_file: ./results/security-results.sarif




     












